steps:
  # 1. Dockerイメージをビルドする
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/notipal-frontend-repo/notipal-frontend:${COMMIT_SHA}', # フロントエンド用のリポジトリ名（例: notipal-frontend-repo）
        '.', # Dockerfileのビルドコンテキストはリポジトリのルートを指定
        '-f',
        'apps/frontend/Dockerfile', # apps/frontend ディレクトリにある Dockerfile を指定
      ]
    # dir はここでは不要。ビルドコンテキストがルートで、Dockerfileのパスを -f で指定してるからな。

# 2. ビルドしたイメージをArtifact Registryにプッシュする
images:
  - 'asia-northeast1-docker.pkg.dev/${PROJECT_ID}/notipal-frontend-repo/notipal-frontend:${COMMIT_SHA}'

# オプション: タイムアウト設定
timeout: '1200s' # 20分（Next.jsのビルドは時間がかかることがあるから、長めにしとくと安心や）

options:
  logging: CLOUD_LOGGING_ONLY
