/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/destinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of destinations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description 送信先のユニークID
                             */
                            id: string;
                            /** @description この送信先を所有するユーザーのID */
                            userId: string;
                            /** @description 送信先の管理名 */
                            name?: string;
                            /**
                             * Format: uri
                             * @description 通知先サービスのWebhook URL
                             */
                            webhookUrl: string;
                            /** @description 作成日時 */
                            createdAt: string;
                            /** @description 更新日時 */
                            updatedAt: string;
                        }[];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description 送信先の管理名 */
                        name?: string;
                        /**
                         * Format: uri
                         * @description 通知先サービスのWebhook URL
                         */
                        webhookUrl: string;
                    };
                };
            };
            responses: {
                /** @description Created destination */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description 送信先のユニークID
                             */
                            id: string;
                            /** @description この送信先を所有するユーザーのID */
                            userId: string;
                            /** @description 送信先の管理名 */
                            name?: string;
                            /**
                             * Format: uri
                             * @description 通知先サービスのWebhook URL
                             */
                            webhookUrl: string;
                            /** @description 作成日時 */
                            createdAt: string;
                            /** @description 更新日時 */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/destinations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A destination */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description 送信先のユニークID
                             */
                            id: string;
                            /** @description この送信先を所有するユーザーのID */
                            userId: string;
                            /** @description 送信先の管理名 */
                            name?: string;
                            /**
                             * Format: uri
                             * @description 通知先サービスのWebhook URL
                             */
                            webhookUrl: string;
                            /** @description 作成日時 */
                            createdAt: string;
                            /** @description 更新日時 */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description 送信先の管理名 */
                        name?: string;
                        /**
                         * Format: uri
                         * @description 通知先サービスのWebhook URL
                         */
                        webhookUrl?: string;
                    };
                };
            };
            responses: {
                /** @description Updated destination */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description 送信先のユニークID
                             */
                            id: string;
                            /** @description この送信先を所有するユーザーのID */
                            userId: string;
                            /** @description 送信先の管理名 */
                            name?: string;
                            /**
                             * Format: uri
                             * @description 通知先サービスのWebhook URL
                             */
                            webhookUrl: string;
                            /** @description 作成日時 */
                            createdAt: string;
                            /** @description 更新日時 */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Destination deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of templates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description テンプレートのユニークID
                             */
                            id: string;
                            /** @description このテンプレートを所有するユーザーのID */
                            userId: string;
                            /** @description テンプレートの管理名 */
                            name: string;
                            /** @description 通知のトリガーとなるNotionデータベースのID */
                            notionDatabaseId: string;
                            /** @description このテンプレートが使用するUser Notion IntegrationのID */
                            userNotionIntegrationId: string | null;
                            /** @description 通知メッセージの本文 */
                            body: string;
                            /** @description 通知条件のリスト (AND条件) */
                            conditions: {
                                /** @description NotionのプロパティIDまたは名前 */
                                propertyId: string;
                                /** @description 比較演算子 */
                                operator: string;
                                /** @description 比較する値 */
                                value?: unknown;
                            }[];
                            /** @description 通知を送信する先のDestinationのID */
                            destinationId: string;
                            /** @description 作成日時 */
                            createdAt: string;
                            /** @description 更新日時 */
                            updatedAt: string;
                        }[];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description テンプレートの管理名 */
                        name: string;
                        /** @description 通知のトリガーとなるNotionデータベースのID */
                        notionDatabaseId: string;
                        userNotionIntegrationId: string;
                        /** @description 通知メッセージの本文 */
                        body: string;
                        /** @description 通知条件のリスト (AND条件) */
                        conditions: {
                            /** @description NotionのプロパティIDまたは名前 */
                            propertyId: string;
                            /** @description 比較演算子 */
                            operator: string;
                            /** @description 比較する値 */
                            value?: unknown;
                        }[];
                        /** @description 通知を送信する先のDestinationのID */
                        destinationId: string;
                    };
                };
            };
            responses: {
                /** @description Created template */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description テンプレートのユニークID
                             */
                            id: string;
                            /** @description このテンプレートを所有するユーザーのID */
                            userId: string;
                            /** @description テンプレートの管理名 */
                            name: string;
                            /** @description 通知のトリガーとなるNotionデータベースのID */
                            notionDatabaseId: string;
                            /** @description このテンプレートが使用するUser Notion IntegrationのID */
                            userNotionIntegrationId: string | null;
                            /** @description 通知メッセージの本文 */
                            body: string;
                            /** @description 通知条件のリスト (AND条件) */
                            conditions: {
                                /** @description NotionのプロパティIDまたは名前 */
                                propertyId: string;
                                /** @description 比較演算子 */
                                operator: string;
                                /** @description 比較する値 */
                                value?: unknown;
                            }[];
                            /** @description 通知を送信する先のDestinationのID */
                            destinationId: string;
                            /** @description 作成日時 */
                            createdAt: string;
                            /** @description 更新日時 */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A template */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description テンプレートのユニークID
                             */
                            id: string;
                            /** @description このテンプレートを所有するユーザーのID */
                            userId: string;
                            /** @description テンプレートの管理名 */
                            name: string;
                            /** @description 通知のトリガーとなるNotionデータベースのID */
                            notionDatabaseId: string;
                            /** @description このテンプレートが使用するUser Notion IntegrationのID */
                            userNotionIntegrationId: string | null;
                            /** @description 通知メッセージの本文 */
                            body: string;
                            /** @description 通知条件のリスト (AND条件) */
                            conditions: {
                                /** @description NotionのプロパティIDまたは名前 */
                                propertyId: string;
                                /** @description 比較演算子 */
                                operator: string;
                                /** @description 比較する値 */
                                value?: unknown;
                            }[];
                            /** @description 通知を送信する先のDestinationのID */
                            destinationId: string;
                            /** @description 作成日時 */
                            createdAt: string;
                            /** @description 更新日時 */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description テンプレートの管理名 */
                        name?: string;
                        /** @description 通知のトリガーとなるNotionデータベースのID */
                        notionDatabaseId?: string;
                        userNotionIntegrationId?: string;
                        /** @description 通知メッセージの本文 */
                        body?: string;
                        /** @description 通知条件のリスト (AND条件) */
                        conditions?: {
                            /** @description NotionのプロパティIDまたは名前 */
                            propertyId: string;
                            /** @description 比較演算子 */
                            operator: string;
                            /** @description 比較する値 */
                            value?: unknown;
                        }[];
                        /** @description 通知を送信する先のDestinationのID */
                        destinationId?: string;
                    };
                };
            };
            responses: {
                /** @description Updated template */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description テンプレートのユニークID
                             */
                            id: string;
                            /** @description このテンプレートを所有するユーザーのID */
                            userId: string;
                            /** @description テンプレートの管理名 */
                            name: string;
                            /** @description 通知のトリガーとなるNotionデータベースのID */
                            notionDatabaseId: string;
                            /** @description このテンプレートが使用するUser Notion IntegrationのID */
                            userNotionIntegrationId: string | null;
                            /** @description 通知メッセージの本文 */
                            body: string;
                            /** @description 通知条件のリスト (AND条件) */
                            conditions: {
                                /** @description NotionのプロパティIDまたは名前 */
                                propertyId: string;
                                /** @description 比較演算子 */
                                operator: string;
                                /** @description 比較する値 */
                                value?: unknown;
                            }[];
                            /** @description 通知を送信する先のDestinationのID */
                            destinationId: string;
                            /** @description 作成日時 */
                            createdAt: string;
                            /** @description 更新日時 */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Template deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/notion-integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of user notion integrations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Notion連携のユニークID
                             */
                            id: string;
                            /** @description この連携を所有するユーザーのID */
                            userId: string;
                            /** @description 連携の管理名 */
                            integrationName: string;
                            /** @description 作成日時 */
                            createdAt: string;
                            /** @description 更新日時 */
                            updatedAt: string;
                        }[];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Created user notion integration */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Notion連携のユニークID
                             */
                            id: string;
                            /** @description この連携を所有するユーザーのID */
                            userId: string;
                            /** @description 連携の管理名 */
                            integrationName: string;
                            /** @description 作成日時 */
                            createdAt: string;
                            /** @description 更新日時 */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/notion-integrations/{integrationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    integrationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User notion integration deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/notion-integrations/{integrationId}/databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    integrationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of user accessible databases */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notion-databases/{databaseId}/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    databaseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of notion database properties */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/notion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Webhook processed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
