export enum ErrorCode {
	VALIDATION_ERROR = "VALIDATION_ERROR",
	UNAUTHENTICATED = "UNAUTHENTICATED",
	FORBIDDEN = "FORBIDDEN",
	NOT_FOUND = "NOT_FOUND",
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
	// NotiPal用のエラーコードを追加
  NOTION_INTEGRATION_NOT_FOUND = "NOTION_INTEGRATION_NOT_FOUND",
  NOTION_API_ERROR = "NOTION_API_ERROR",
  TEMPLATE_NOT_FOUND = "TEMPLATE_NOT_FOUND",
  DESTINATION_NOT_FOUND = "DESTINATION_NOT_FOUND",
}; 
