name: Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/deploy-frontend.yaml'
      - 'turbo.json'
      - 'package.json'
      - 'bun.lock'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/937400838385/locations/global/workloadIdentityPools/notipal-wif-pool/providers/notipal-gh-provider-v3'
          service_account: 'notipal-cloudbuild-sa@notipal-prod.iam.gserviceaccount.com'

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: notipal-prod

      - name: Submit build to Cloud Build for Frontend
        run: gcloud builds submit . --project=notipal-prod --config=apps/frontend/cloudbuild-frontend.yaml --substitutions="COMMIT_SHA=${{ github.sha }},_NEXT_PUBLIC_NODE_ENV=production,_NEXT_PUBLIC_FIREBASE_API_KEY_PROD=${{ secrets.FRONTEND_FIREBASE_API_KEY_PROD }},_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_PROD=${{ secrets.FRONTEND_FIREBASE_AUTH_DOMAIN_PROD }},_NEXT_PUBLIC_FIREBASE_PROJECT_ID_PROD=${{ secrets.FRONTEND_FIREBASE_PROJECT_ID_PROD }},_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET_PROD=${{ secrets.FRONTEND_FIREBASE_STORAGE_BUCKET_PROD }},_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID_PROD=${{ secrets.FRONTEND_FIREBASE_MESSAGING_SENDER_ID_PROD }},_NEXT_PUBLIC_FIREBASE_APP_ID_PROD=${{ secrets.FRONTEND_FIREBASE_APP_ID_PROD }},_NEXT_PUBLIC_API_BASE_URL_PROD=${{ secrets.FRONTEND_API_BASE_URL_PROD }},_NEXT_PUBLIC_API_BASE_URL_DEV=http://localhost:8080,_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID_PROD=${{ secrets.FRONTEND_FIREBASE_MEASUREMENT_ID_PROD }}"

      - name: Deploy to Cloud Run
        run: gcloud run deploy notipal-frontend-service --image asia-northeast1-docker.pkg.dev/notipal-prod/notipal-frontend-repo/notipal-frontend:${{ github.sha }} --region asia-northeast1 --platform managed --allow-unauthenticated --port 3000 --set-env-vars "NEXT_PUBLIC_NODE_ENV=production,NEXT_PUBLIC_API_BASE_URL_PROD=${{ secrets.FRONTEND_API_BASE_URL_PROD }},NEXT_PUBLIC_FIREBASE_API_KEY_PROD=${{ secrets.FRONTEND_FIREBASE_API_KEY_PROD }},NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_PROD=${{ secrets.FRONTEND_FIREBASE_AUTH_DOMAIN_PROD }},NEXT_PUBLIC_FIREBASE_PROJECT_ID_PROD=${{ secrets.FRONTEND_FIREBASE_PROJECT_ID_PROD }},NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET_PROD=${{ secrets.FRONTEND_FIREBASE_STORAGE_BUCKET_PROD }},NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID_PROD=${{ secrets.FRONTEND_FIREBASE_MESSAGING_SENDER_ID_PROD }},NEXT_PUBLIC_FIREBASE_APP_ID_PROD=${{ secrets.FRONTEND_FIREBASE_APP_ID_PROD }},NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID_PROD=${{ secrets.FRONTEND_FIREBASE_MEASUREMENT_ID_PROD }}" --quiet

      - name: Deployment Notification
        if: success()
        run: echo "✅ Frontend deployed successfully to Cloud Run!"
